[api_keys]
PINECONE_API_KEY = "285cd9e0-faa5-4453-ada7-a05f7af67b93"
GOOGLE_API_KEY = "AIzaSyByFoyQYuNDC9jsCwdNfs8_UhgmPNJWHJI"
GROQ_API_KEY = "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"